services:
  backend_app:
    container_name: backend_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:

      DB_INIT_MODE: create
    volumes:
      - ./:/usr/backend
    ports:
      - "8001:8000"

